### ISSUE TITLE
Classcraft API Access

### ISSUE THREAD

**Issue by davidchak90** [classcraft/classcraft-api-issues#1]
Hi Simon,

I was told by Nicolas to contact you here if i have any question.

I am trying to perform mutation query for the data, i couldnt seem to get it to work. Is this the right query message to use?
(I am testing this on an API explorer)

mutation{
  applyCustomGPBehavior(value: 100, description: "A", characterId: "nWRuQHYxFjYAopBFp", classId: "k5QfPZJKQpcsPB6pS"): Character  
}

**Comment by davidchak90** [comment]
Nevermind. ignore me. I found my mistake. 

mutation{
  applyCustomGPBehavior(value: 100, 
    description: "Fun", 
    characterId: "nWRuQHYxFjYAopBFp", 
    classId: "k5QfPZJKQpcsPB6pS"){
    _id 
  }
}

**Comment by simonbelanger** [comment]
@davidchak90 Glad you figured this one out! Don't hesitate if you have other questions, but it's the end of day here so I'll not be able to answer before tomorrow!
