### ISSUE TITLE
Unable to modify HP

### ISSUE THREAD

**Issue by davidchak90** [classcraft/classcraft-api-issues#2]
Hi,

I couldnt seem to mutate HP information.

Query:
```
mutation{
  applyCustomHPBehavior(value: 15, 
    description: "Fun", 
    characterId: "nWRuQHYxFjYAopBFp", 
    classId: "k5QfPZJKQpcsPB6pS"){
    _id 
      
    
  }
}
```
It returns
```
{
  "data": {
    "applyCustomHPBehavior": {
      "_id": "9NXSsgrXunWxLt4F4"
    }
  }
}
```

No changes is made to classcraft. Also, what is the id that it returns? It says it returns "delayedDamafe". What is delayedDamage?

**Comment by simonbelanger** [comment]
Here's a help article that explains what are delayed damage better than I could 😅 :

https://help.classcraft.com/hc/en-us/articles/218411487-Negative-behaviors-Health-Points-HP-and-falling#delayed-damage

The reason why the API only creates delayed damage is to give the chance to students to use their powers on the damage if they want to.

**Comment by davidchak90** [comment]
Would it be possible to bypass this? So that the damage cannot be mitigated.

**Comment by simonbelanger** [comment]
No, because that would go against the game mechanisms, students should always have the possibility to use their powers on the damage if they can/want to.

**Comment by davidchak90** [comment]
I see. Maybe i will explain abit what i am trying to do with the API.

We are running a financial simulation game - and a part of it involves the students being able to purchase houses, cars, luxuries, and of course paying for insurance and all. 

Since it isnt built into Classcraft system, we will be creating a separate system utilizing Google Forms and Google Sheets to manage all these transactions (for example, if you fill in the option of buying a car on Goolge Sheet, this changes in your GP would be reflected back in Classcraft). This feature is available from the API

Similarly, you could be hit by a disease and if you dont have insurance, your HP will be reduced <- this part we could do it in GSheet or in Classcraft (via random event) - i was just trying see how we could do that in Gsheet,

Alternately, there may be situations where we need to mass update students information (the game will be attended by 60 people) - i can then push the changes from my Google Sheet table back into Classcraft. 

Not sure if anyone has ever done it before - but I have managed to 
1) Establish ouath token between my apps script and classcraft
2) Pull data from classcraft and display them on a google sheet table
3) Push data from the google sheet table back into classcraft (I am able to do it with GP and XP. But no luck with HP yet)

We foresee the possibility of using classcraft for all other programs that we do, following this Gsheet/GForm + Classcraft system. 

One suggestion though - I know the characters are identified with the char_id, i wonder if we can identify students by their email - for example, each student is identified by their email or other unique identifier. Not that this is important bcause currently, we are identifying uniquely each student based ont he character_id (which i assume is non permutable and act as the primary key to the students).

Similarly, i wonder if the team inforamtion can also be tied to the character. For now, the only way to access each team is to go into a team and then accesing its characters. I think it would be good also fo rthis information to be stored in character so that when i query each character, I will be able to get their team id.

**Comment by simonbelanger** [comment]
For the HP, I don't see any other solution than having the teacher applying the delayed damage manually through his Classcraft account.

For the email on the `Student` entity and accessing the team directly through the `Character` entity, those are very good suggestions although I must say that we are currently in very busy period right now (back to school in US) and improving the API might not be in our top priorities on a short term.

**Comment by davidchak90** [comment]
Sure no problem. This is my first time dealing with GraphQL (in fact, my first time interfacing with an external API). I got to say, I am learning alot through this experience. My primary coding environment is with data analytical and processing - so this is a new experience for me pretty much. 

As of now I think i am able to achieve what i want to achieve, 

Another sidenote, your API explorer doesnt seem to work very well - lets say my dev account is account A and my actual camp account is account B. The API explorer for account A cant seem to use the token that is granted by account B.

All of my testings are done with an external API explorer instead, which allows me to modify the header to include the bearer token (https://graphiql-online.com/graphiql). Perhaps this is also something that can be improved.

However, that being said, I would imagine people who request for the API access probably know what they are doing.

Side question: - do you guys have people like me who are extending the Classcraft functionality via API? If so, do you have a community page or a group that we can share experiences and best practices / troubleshooting?  Or is this the only place where classcraft API user can discuss (if so...this place is really...quiet...)

**Comment by simonbelanger** [comment]
Here would be the place to discuss and share, but I must admit that we might not promote this communication channel as much as we could 😄 . Also we still don't have a lot API users yet...

**Comment by davidchak90** [comment]
Awesome! Thanks! Will let you know if any problems arise. Thanks for the API.
